protect_element=function(x,element){
  if(str_detect(x,element)){
  parts=str_split_fixed(x,element,n=2)
  replacement=str_replace_all(element,"_","xxx")
  replacement=str_replace_all(replacement,"\\.","yyy")
  x=str_c(parts[1],
          replacement,
          parts[2])
  }
  return(x)
}
